[package]
name = "class-schedule"
version = "0.1.0"
authors = ["Marcus Ball <marcus.ball@live.com>"]

[dependencies]
toml = "0.4.1"
serde = "1.0.6"
serde_derive = "1.0"
regex = "0.2.1"
lazy_static = "0.2.8"